# Model arguments
model_revision: main
torch_dtype: float32
bf16: false
tf32: false

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Training arguments
max_steps: 50 # Original 450
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 5.0e-7 #5.0e-7 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.1

# GRPO arguments
num_workers: 6
ddp_enabled: false
torch_distributed_backend: "gloo"
torch_num_threads: 8
torch_intraop_threads: 8
torch_interop_threads: 1
pin_memory: false
non_blocking: false
prefetch_factor: 2
torch_use_deterministic_algorithms: false
torch_use_cpu_affinity: true
use_vllm: false
num_generations: 1
per_device_train_batch_size: 1
beta: 0.01 # 0.001, 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 128
max_completion_length: 128

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 50
seed: 42

# Script arguments
max_rounds: 10000
no_cuda: true

# Model-specific arguments
model_name_or_path: unsloth/Qwen2.5-0.5B-Instruct
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm
