# Model arguments
model_name_or_path: Gensyn/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Training arguments
max_steps: 31         # Lebih masuk akal dari 20 untuk pelatihan nyata
gradient_accumulation_steps: 8  # Efektif batch size = 8 * per_device
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 7.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.1      # warmup lebih banyak untuk stabilisasi

per_device_train_batch_size: 1  # Supaya muat di GPU terbatas

# GRPO arguments
use_vllm: false        # VLLM kurang cocok untuk LoRA + training kecil
num_generations: 4
beta: 0.01             # Reward lebih kuat agar GRPO belajar
max_prompt_length: 128
max_completion_length: 512

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
seed: 42

# LoRA Tuning (Jika support)
use_lora: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]  # Sesuaikan dengan arsitektur Qwen2.5

# Script arguments (untuk Gensyn)
public_maddr: "/ip4/38.101.215.12/tcp/30002"
host_maddr: "/ip4/0.0.0.0/tcp/38331"
max_rounds: 10000

# Output
output_dir: runs/gsm8k/multinode/Qwen2.5-1.5B-Instruct-Gensyn-Swarm